language: java
sudo: false
install: true
script: ./local_travis.sh

jdk:
  - oraclejdk7
  - oraclejdk8

env:
  - JOB=CI
  - JOB=ITS IT_CATEGORY=issue
  - JOB=ITS IT_CATEGORY=analysis

cache:
  directories:
    - '$HOME/.m2/repository'
